//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumLabels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.Core.Resources.EnumLabels", typeof(EnumLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Par le Client.
        /// </summary>
        public static string DinnerPaidBy_Client {
            get {
                return ResourceManager.GetString("DinnerPaidBy_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employé.
        /// </summary>
        public static string DinnerPaidBy_Employee {
            get {
                return ResourceManager.GetString("DinnerPaidBy_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Senza.
        /// </summary>
        public static string DinnerPaidBy_None {
            get {
                return ResourceManager.GetString("DinnerPaidBy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrateur.
        /// </summary>
        public static string UserRole_Admin {
            get {
                return ResourceManager.GetString("UserRole_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employé.
        /// </summary>
        public static string UserRole_Employee {
            get {
                return ResourceManager.GetString("UserRole_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technicien.
        /// </summary>
        public static string UserRole_Technician {
            get {
                return ResourceManager.GetString("UserRole_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extra-Horaire.
        /// </summary>
        public static string WorkSessionType_Extraordinary {
            get {
                return ResourceManager.GetString("WorkSessionType_Extraordinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nuit.
        /// </summary>
        public static string WorkSessionType_Night {
            get {
                return ResourceManager.GetString("WorkSessionType_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autre.
        /// </summary>
        public static string WorkSessionType_Other {
            get {
                return ResourceManager.GetString("WorkSessionType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déplacement.
        /// </summary>
        public static string WorkSessionType_OutOfTown {
            get {
                return ResourceManager.GetString("WorkSessionType_OutOfTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ordinaire.
        /// </summary>
        public static string WorkSessionType_Regular {
            get {
                return ResourceManager.GetString("WorkSessionType_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maladie.
        /// </summary>
        public static string WorkSessionType_Sickness {
            get {
                return ResourceManager.GetString("WorkSessionType_Sickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Congé.
        /// </summary>
        public static string WorkSessionType_Vacation {
            get {
                return ResourceManager.GetString("WorkSessionType_Vacation", resourceCulture);
            }
        }
    }
}
