//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⌂ Retour à l’accueil.
        /// </summary>
        internal static string AdminDashboard_BackToHome {
            get {
                return ResourceManager.GetString("AdminDashboard_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string AdminDashboard_Error {
            get {
                return ResourceManager.GetString("AdminDashboard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Échec du chargement des utilisateurs..
        /// </summary>
        internal static string AdminDashboard_LoadUsers_Error {
            get {
                return ResourceManager.GetString("AdminDashboard_LoadUsers_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rafraîchir.
        /// </summary>
        internal static string AdminDashboard_Refresh {
            get {
                return ResourceManager.GetString("AdminDashboard_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard.
        /// </summary>
        internal static string AdminDashboard_Tab {
            get {
                return ResourceManager.GetString("AdminDashboard_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard Admin.
        /// </summary>
        internal static string AdminDashboard_Title {
            get {
                return ResourceManager.GetString("AdminDashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⌂ Retour à l’accueil.
        /// </summary>
        internal static string EndSession_BackToHome {
            get {
                return ResourceManager.GetString("EndSession_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qui a payé le dîner ?.
        /// </summary>
        internal static string EndSession_DinnerPaidBy {
            get {
                return ResourceManager.GetString("EndSession_DinnerPaidBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer la session.
        /// </summary>
        internal static string EndSession_EndSessionBtn {
            get {
                return ResourceManager.GetString("EndSession_EndSessionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune session à terminer..
        /// </summary>
        internal static string EndSession_Error_NoSession {
            get {
                return ResourceManager.GetString("EndSession_Error_NoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string EndSession_Error_OK {
            get {
                return ResourceManager.GetString("EndSession_Error_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string EndSession_Error_Title {
            get {
                return ResourceManager.GetString("EndSession_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localisation indisponible.
        /// </summary>
        internal static string EndSession_LocationUnavailable {
            get {
                return ResourceManager.GetString("EndSession_LocationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune session en cours.
        /// </summary>
        internal static string EndSession_NoSessionInProgress {
            get {
                return ResourceManager.GetString("EndSession_NoSessionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos session en cours.
        /// </summary>
        internal static string EndSession_SessionInfo {
            get {
                return ResourceManager.GetString("EndSession_SessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session en cours :.
        /// </summary>
        internal static string EndSession_SessionInProgress {
            get {
                return ResourceManager.GetString("EndSession_SessionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à démarrée à.
        /// </summary>
        internal static string EndSession_StartedAt {
            get {
                return ResourceManager.GetString("EndSession_StartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer la session.
        /// </summary>
        internal static string EndSession_Title {
            get {
                return ResourceManager.GetString("EndSession_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heures de déplacement.
        /// </summary>
        internal static string EndSession_TravelHours {
            get {
                return ResourceManager.GetString("EndSession_TravelHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minutes de déplacement.
        /// </summary>
        internal static string EndSession_TravelMinutes {
            get {
                return ResourceManager.GetString("EndSession_TravelMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard Admin.
        /// </summary>
        internal static string Home_AdminDashboard {
            get {
                return ResourceManager.GetString("Home_AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas les droits pour accéder à l&apos;Admin Dashboard..
        /// </summary>
        internal static string Home_AdminDashboard_Alert_AccessDenied {
            get {
                return ResourceManager.GetString("Home_AdminDashboard_Alert_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès refusé.
        /// </summary>
        internal static string Home_AdminDashboard_Alert_Title {
            get {
                return ResourceManager.GetString("Home_AdminDashboard_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer la session.
        /// </summary>
        internal static string Home_EndSession {
            get {
                return ResourceManager.GetString("Home_EndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune session n&apos;est en cours. Veuillez d&apos;abord démarrer une session..
        /// </summary>
        internal static string Home_EndSession_Alert_NoSession {
            get {
                return ResourceManager.GetString("Home_EndSession_Alert_NoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de session en cours.
        /// </summary>
        internal static string Home_EndSession_Alert_Title {
            get {
                return ResourceManager.GetString("Home_EndSession_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        internal static string Home_History {
            get {
                return ResourceManager.GetString("Home_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string Home_OK {
            get {
                return ResourceManager.GetString("Home_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer une session.
        /// </summary>
        internal static string Home_StartSession {
            get {
                return ResourceManager.GetString("Home_StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez déjà une session non terminée. Veuillez d&apos;abord terminer cette session..
        /// </summary>
        internal static string Home_StartSession_Alert_AlreadyStarted {
            get {
                return ResourceManager.GetString("Home_StartSession_Alert_AlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session en cours.
        /// </summary>
        internal static string Home_StartSession_Alert_Title {
            get {
                return ResourceManager.GetString("Home_StartSession_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        internal static string Home_Tab {
            get {
                return ResourceManager.GetString("Home_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login_Error_EmptyFields.
        /// </summary>
        internal static string Login_Error_EmptyFields {
            get {
                return ResourceManager.GetString("Login_Error_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la connexion. Veuillez réessayer..
        /// </summary>
        internal static string Login_Error_Exception {
            get {
                return ResourceManager.GetString("Login_Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Échec de la connexion : identifiants invalides ou erreur serveur..
        /// </summary>
        internal static string Login_Error_Invalid {
            get {
                return ResourceManager.GetString("Login_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Login_Error_Label {
            get {
                return ResourceManager.GetString("Login_Error_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Login_Error_Locked {
            get {
                return ResourceManager.GetString("Login_Error_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string Login_Flyout_Title {
            get {
                return ResourceManager.GetString("Login_Flyout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion en cours….
        /// </summary>
        internal static string Login_Loading {
            get {
                return ResourceManager.GetString("Login_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string Login_Placeholder_Password {
            get {
                return ResourceManager.GetString("Login_Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez votre nom d’utilisateur.
        /// </summary>
        internal static string Login_Placeholder_Username {
            get {
                return ResourceManager.GetString("Login_Placeholder_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d’utilisateur.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays.
        /// </summary>
        internal static string Registration_Country {
            get {
                return ResourceManager.GetString("Registration_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string Registration_Email {
            get {
                return ResourceManager.GetString("Registration_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Échec de l&apos;inscription..
        /// </summary>
        internal static string Registration_Failed {
            get {
                return ResourceManager.GetString("Registration_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        internal static string Registration_FirstName {
            get {
                return ResourceManager.GetString("Registration_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string Registration_LastName {
            get {
                return ResourceManager.GetString("Registration_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string Registration_Password {
            get {
                return ResourceManager.GetString("Registration_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        internal static string Registration_RegisterBtn {
            get {
                return ResourceManager.GetString("Registration_RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rôle.
        /// </summary>
        internal static string Registration_Role {
            get {
                return ResourceManager.GetString("Registration_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription réussie !.
        /// </summary>
        internal static string Registration_Success {
            get {
                return ResourceManager.GetString("Registration_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        internal static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        internal static string Registration_Town {
            get {
                return ResourceManager.GetString("Registration_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        internal static string Registration_Username {
            get {
                return ResourceManager.GetString("Registration_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⌂ Retour à l’accueil.
        /// </summary>
        internal static string StartSession_BackToHome {
            get {
                return ResourceManager.GetString("StartSession_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de démarrer la session..
        /// </summary>
        internal static string StartSession_Error_CannotStart {
            get {
                return ResourceManager.GetString("StartSession_Error_CannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun utilisateur connecté..
        /// </summary>
        internal static string StartSession_Error_NoUser {
            get {
                return ResourceManager.GetString("StartSession_Error_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string StartSession_Error_OK {
            get {
                return ResourceManager.GetString("StartSession_Error_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string StartSession_Error_Title {
            get {
                return ResourceManager.GetString("StartSession_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inclut du déplacement ?.
        /// </summary>
        internal static string StartSession_IncludesTravel {
            get {
                return ResourceManager.GetString("StartSession_IncludesTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localisation indisponible.
        /// </summary>
        internal static string StartSession_LocationUnavailable {
            get {
                return ResourceManager.GetString("StartSession_LocationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez le type de session.
        /// </summary>
        internal static string StartSession_SelectType {
            get {
                return ResourceManager.GetString("StartSession_SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer la session.
        /// </summary>
        internal static string StartSession_StartBtn {
            get {
                return ResourceManager.GetString("StartSession_StartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer une session.
        /// </summary>
        internal static string StartSession_Title {
            get {
                return ResourceManager.GetString("StartSession_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⌂ Retour à l’accueil.
        /// </summary>
        internal static string TimeEntries_BackToHome {
            get {
                return ResourceManager.GetString("TimeEntries_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🍽 Dîner : {0}.
        /// </summary>
        internal static string TimeEntries_DinnerPaid {
            get {
                return ResourceManager.GetString("TimeEntries_DinnerPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📍 Fin: {0}.
        /// </summary>
        internal static string TimeEntries_EndAddress {
            get {
                return ResourceManager.GetString("TimeEntries_EndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Échec du chargement des pointages..
        /// </summary>
        internal static string TimeEntries_FailedToLoad {
            get {
                return ResourceManager.GetString("TimeEntries_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non authentifié..
        /// </summary>
        internal static string TimeEntries_NotAuthenticated {
            get {
                return ResourceManager.GetString("TimeEntries_NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📍 Début: {0}.
        /// </summary>
        internal static string TimeEntries_StartAddress {
            get {
                return ResourceManager.GetString("TimeEntries_StartAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique des pointages.
        /// </summary>
        internal static string TimeEntries_Title {
            get {
                return ResourceManager.GetString("TimeEntries_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⏱ Durée totale : {0:%h}h {0:%m}m.
        /// </summary>
        internal static string TimeEntries_TotalDuration {
            get {
                return ResourceManager.GetString("TimeEntries_TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🚗 Trajet inclus : {0}.
        /// </summary>
        internal static string TimeEntries_TravelIncluded {
            get {
                return ResourceManager.GetString("TimeEntries_TravelIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🚕 Temps de trajet : {0:hh\:mm}.
        /// </summary>
        internal static string TimeEntries_TravelTime {
            get {
                return ResourceManager.GetString("TimeEntries_TravelTime", resourceCulture);
            }
        }
    }
}
